### ISSUE TITLE
Error install uro

### ISSUE THREAD

**Issue by mjulda** [s0md3v/uro#29] opened 2022-10-12 14:38 UTC
suya has the error...
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behavior with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

I've done the steps above but haven't found a bright spot :(

can anyone help me???

**Comment by Tripse** [comment] 2022-10-17 21:59
it's so easy to be solved,are you linux users? It's a notice，that's need a common users privilege :）not is root

**Comment by s0md3v** [comment] 2022-11-13 21:33
This error is not caused by or coming from uro, closing.

**Closed by s0md3v** 2022-11-13 21:33 UTC
Labels: invalid
