### ISSUE TITLE
false positive 

### ISSUE THREAD

**Issue by c4ir0** [s0md3v/uro#28] opened 2022-09-04 21:00 UTC
hmmm ...
![sas](https://user-images.githubusercontent.com/108268587/188333289-b68a73b1-4606-4f81-8a2c-2b05b1e7a51f.JPG)

**Comment by mjulda** [comment] 2022-10-12 14:40
I've followed the steps to install uro, but it's still an error.
can you share how to install?

**Comment by mjulda** [comment] 2022-10-12 14:51
![Screenshot at 2022-10-12 21-51-01](https://user-images.githubusercontent.com/49862728/195375797-bdacf3a3-4c11-4f70-8f9d-b332b41bf76b.png)

**Comment by mjulda** [comment] 2022-10-12 14:57
bash: uro: command not found

**Comment by mjulda** [comment] 2022-10-12 15:02
> ![Screenshot at 2022-10-12 21-51-01](https://user-images.githubusercontent.com/49862728/195375797-bdacf3a3-4c11-4f70-8f9d-b332b41bf76b.png)

same error as this..

sudo pip3 install uro
Requirement already satisfied: uro in /usr/local/lib/python3.9/dist-packages (0.0.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by s0md3v** [comment] 2022-11-13 21:28
`pip3 install uro --user`

**Comment by s0md3v** [comment] 2022-11-13 21:29
Hi @c4ir0, what's the "false positive" here? It seems to work as intended.

**Comment by s0md3v** [comment] 2022-11-13 21:51
I see. I will take a look, thanks for the report!

**Comment by s0md3v** [comment] 2022-11-13 22:15
This issue has been fixed in the git repo, the pip release will be updated later with a couple of more enhancements.

For the people are having trouble installing `uro` and are spamming here instead of reading what error says - install it with a non-root user with the `--user` flag. Also, if what I'm saying doesn't work for you, don't comment here. My job was to create a tool which I did, this is not customer support.

**Closed by s0md3v** 2022-11-13 22:15 UTC
Labels: bug
